import Head from 'next/head'
import MainContainer from '../layout/MainContainer'
import Banner from './Banner'
import Sobre from './Sobre'
import Fotos from './Fotos'
import Local from './Local'

export default function Home() {
  return (
    <>
      <Head>
        <title>Play Dj's</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <MainContainer>
        <Sobre/>
        <div className="spacing"></div>
        <Fotos/>
        <div className="spacing"></div>
        <Local/>
      </MainContainer>
    </>
  )
}
